version: '3.8'
services:
  sadtalker:
    image: paidax/faster-sadtalker-api:0.1.3
    container_name: sadtalker
    privileged: true
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./results:/home/SadTalker/results
    ports:
      - 10364:10364
    environment:
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - TTS_SERVER=http://tts:9566/tts
    command: uvicorn main:app --reload --port 10364 --host 0.0.0.0
    runtime: nvidia
  tts:
    container_name: tts
    image: paidax/tts_modelscope:0.1.3
    privileged: true
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
    ports:
      - 9566:9566
    restart: always
    environment:
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    command: uvicorn main:app --reload --port 9566 --host 0.0.0.0
    runtime: nvidia
