version: '3.8'
services:
  sadtalker:
    image: paidax/faster-sadtalker-api:0.1.3
    container_name: sadtalker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - TTS_SERVER=http://tts:9566/tts
    volumes:
      - ./checkpoints:/home/SadTalker/checkpoints
      - ./gfpgan/weights:/home/SadTalker/gfpgan/weights
      - ./results:/home/SadTalker/results
      - /usr/lib/wsl:/usr/lib/wsl
    ports:
      - 10364:10364
    privileged: true
    command: uvicorn main:app --reload --port 10364 --host 0.0.0.0
  tts:
    container_name: tts
    image: paidax/tts_modelscope:0.1.3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
    volumes:
      - /usr/lib/wsl:/usr/lib/wsl
    ports:
      - 9566:9566
    restart: always
    privileged: true
    command: uvicorn main:app --reload --port 9566 --host 0.0.0.0
